### ISSUE TITLE
LabelTable not returned

### ISSUE THREAD

**Issue by neurolabusc** [Washington-University/cifti-matlab#6]
This library does not return the color tables for Parcellation maps for [reference datasets](https://balsa.wustl.edu/). The cifti file reports `CIFTI_INDEX_TYPE_LABELS` and the Matlab code dutifully reads the `LabelTable` Colors. However, the Matlab code never returns the color lookup table values to the user. Specifically, consider the XML
```
<Label Key="360" Red="0.478431" Green="0.145098" Blue="0.286275" Alpha="1">L_p24_ROI</Label>
```
which defines vertices of index 360 to have specific RGBA values and the name `L_p24_ROI`. While the Matlab code parses this XML table, it is not returned as part of the struct:

```
cii = ft_read_cifti('Q1-Q6_RelatedParcellation210.CorticalAreas_dil_Final_Final_Areas_Group_Colors.32k_fs_LR.dlabel.nii')

  struct with fields:

                 dimord: 'pos'
               indexmax: [64984×1 double]
                    hdr: [1×1 struct]
                   unit: 'mm'
         brainstructure: [64984×1 double]
    brainstructurelabel: {'CORTEX_LEFT'  'CORTEX_RIGHT'}
                    pos: [64984×3 double]


```

**Comment by coalsont** [comment]
Please try the `read_cifti` function from the root folder of the latest version, the label tables should be inside the appropriate diminfo element.  I'm not currently planning on changing how the ft_ functions work.

`read_cifti` is intended to be backwards compatible with the common usage of `ciftiopen`, and represent the information mostly the same way it is stored in the cifti file, so unfortunately it will require some work to adapt code that was using ft_ functions to it.

**Comment by coalsont** [comment]
Alternatively, if you want to stick with the ft_ functions because you have already used them extensively in your codebase, you might raise this issue with fieldtrip itself, and see if their cifti IO can be made to expose label tables:

https://github.com/fieldtrip/fieldtrip

**Comment by neurolabusc** [comment]
OK. Is there a CIfTI optimizer that would reduce file size and enhance read speed while maintaining compatibility? I recognize that CIfTI format forbids compression, but some simple optimization of the files could accelerate downloads, reduce disk usage and yield faster loads. In the example above, the CIfTI uses an indexed palette with 361 levels (0..360). However, the file contains 59412 float32 values that is expanded to 64984 vertices using ASCII VertexIndices. Why not just store the unique 361 INT16 values (0..360) with the ASCII VertexIndices? Alternatively, explicitly store all 64984 values as INT16 without the ASCII VertexIndices? The ASCII indices seem to yield very slow reading with Matlab.

One could get even better performance by adopting a simpler format. In brief testing, a simpler format (compressed mz3) yielded files that were loaded 20 times faster (with Matlab) and 80 times smaller (though one could trade off between these two metrics by selecting compression).

**Comment by coalsont** [comment]
You can compress them for download, as long as you decompress them before use.

The dlabel format allows having multiple different label maps in a single file, so putting the values in the XML would need more complication (in addition to completely changing the design concepts of cifti).  Adopting a different container format would also be a major change to all software that uses cifti.  wb_command can write cifti with a different datatype, such as 16 bit integer, which could be added to write_cifti, with some effort.

Unless you have a very large number of dlabel files, the big cifti files in a dataset are usually going to be the dtseries (unless you distribute dconn files - we generally don't yet because most of them can be fairly easily regenerated from dtseries).

The version of matlab we currently use typically takes 5 or more seconds to just launch the command line, no jvm mode, while loading a dlabel with this library was around 1 second, so unless you are loading dozens of files and doing something trivially fast with them, it doesn't sound like there is all that much time savings to be had even with a drastic format change.  If saving seconds is very important to your use case, you should probably be writing in c++ or another compiled language (we have a c++ cifti library available).  You can, of course, internally use whatever other formats you want, this library is just improved compatibility with file formats already in use by other software.

**Comment by coalsont** [comment]
Also, I believe the main time spent reading cifti with this library is in the XML code (as long as your filesystem is reasonably fast, that is), so putting more things into the XML could make it slower, not faster.  The data matrix reading and byteswapping/conversion is handled by matlab in a single call to fread, which matlab has hopefully optimized.

**Comment by coalsont** [comment]
I looked up the time testing I had done, and it turns out dlabel is substantially slower than dscalar of equivalent size - this means that the label tables, not the vertex indices, are the limiting factor in the dlabel XML parsing speed - the vertex indices are actually fairly fast to parse in my testing (it just hands the whole string of numbers and spaces off to a matlab conversion function).

The relative slowness in dlabel seemed to be mostly in the base XML library (before it gets to any cifti-XML-specific code), and using the compiled mex for the string matching makes the XML library take half the time on the test dlabel, so presumably it is because of the nesting of many tags, and possibly having many attributes.

Regardless, the cifti-2 format specification has been finalized since 2014, and can't have any drastic changes to its organization until cifti-3.
